"""Render a DXF file to a PNG preview image."""

from __future__ import annotations

from pathlib import Path

import ezdxf
import matplotlib
from ezdxf.addons.drawing import Frontend, RenderContext
from ezdxf.addons.drawing.matplotlib import MatplotlibBackend
from PIL import Image

matplotlib.use("Agg")  # headless backend; safe in Docker / no DISPLAY


def render(dxf_path: Path, png_path: Path, *, max_dim: int = 1200) -> Path:
    """Render *dxf_path* to *png_path*.

    Parameters
    ----------
    dxf_path:
        Source DXF file. Must exist.
    png_path:
        Destination PNG path. Parent dirs are created. Will be overwritten.
    max_dim:
        Cap the longer image edge at this many pixels, preserving aspect.
        Values <= 0 disable downscaling.

    Returns
    -------
    Path
        The same path as ``png_path``.
    """
    dxf_path = Path(dxf_path)
    png_path = Path(png_path)
    if not dxf_path.exists():
        raise FileNotFoundError(f"dxf not found: {dxf_path}")
    png_path.parent.mkdir(parents=True, exist_ok=True)

    doc = ezdxf.readfile(str(dxf_path))
    msp = doc.modelspace()

    _render_to_file(doc, msp, png_path)

    if max_dim > 0:
        _downscale_in_place(png_path, max_dim)

    return png_path


def _render_to_file(doc, msp, png_path: Path) -> None:
    """Render *msp* into *png_path* with pure-black background and white lines.

    DXF entities generated by image_to_dxf have color BYLAYER (256)
    inheriting from a layer whose color is typically 7 (white/black).
    On a white matplotlib canvas those lines are invisible. We force all
    entities to white and use a pure-black background for contrast.
    """
    import matplotlib.pyplot as plt

    # Force all entities to white (visible on black background).
    for entity in msp:
        entity.dxf.color = 7  # white

    # Auto-zoom: calculate the bounding box of all entities.
    try:
        from ezdxf import bbox
        bbox_extents = bbox.extents(msp)
        if bbox_extents is not None:
            (min_x, min_y), (max_x, max_y) = bbox_extents
            width = max_x - min_x
            height = max_y - min_y
            if width > 0 and height > 0:
                scale = 8.0 / max(width, height)
                fig_w = max(4.0, width * scale)
                fig_h = max(3.0, height * scale)
            else:
                fig_w, fig_h = 8.0, 6.0
        else:
            fig_w, fig_h = 8.0, 6.0
    except Exception:
        fig_w, fig_h = 8.0, 6.0

    fig = plt.figure(figsize=(fig_w, fig_h), dpi=100, facecolor="black")
    ax = fig.add_axes([0.05, 0.05, 0.9, 0.9])
    ax.set_facecolor("black")
    ax.set_axis_off()
    backend = MatplotlibBackend(ax)
    Frontend(RenderContext(doc), backend).draw_layout(msp, finalize=True)
    fig.savefig(str(png_path), format="png", dpi=100, facecolor=fig.get_facecolor())
    plt.close(fig)


def _downscale_in_place(png_path: Path, max_dim: int) -> None:
    """Resize *png_path* so the longer edge is at most *max_dim* pixels."""
    img = Image.open(str(png_path))
    nw, nh = img.size
    if max(nw, nh) <= max_dim:
        img.close()
        return
    scale = max_dim / max(nw, nh)
    new_size = (max(1, int(nw * scale)), max(1, int(nh * scale)))
    resized = img.resize(new_size, Image.LANCZOS)
    resized.save(str(png_path))
    img.close()
    resized.close()
